name: Build and Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Build
        run: make

      - name: Rename
        run: mv bin/PasswordManager PasswordManager-${{ github.ref_name }}-linux-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: PasswordManager-${{ github.ref_name }}-linux-x86_64
          path: ./PasswordManager-${{ github.ref_name }}-linux-x86_64
          retention-days: 1

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-linux]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: PasswordManager-${{ github.ref_name }}-linux-x86_64

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: false
          artifacts: PasswordManager-${{ github.ref_name }}-linux-x86_64
